name: 'golangci-lint'
on:
  pull_request:
  push:
    branches:
      - 'master'
  workflow_dispatch:

permissions:
  contents: 'read'
  pull-requests: 'read'
  checks: 'write'

jobs:
  golangci:
    name: 'lint'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/setup-go@v5'
        with:
          cache: false
          go-version: '^1.23'
      - uses: 'actions/checkout@v4'
      - uses: 'golangci/golangci-lint-action@v6'
        with:
          version: 'latest'
          args: '--timeout=60m'
          only-new-issues: true
          skip-cache: true

